
export default function PrivacyPolicy() {
  return (
    <div className="max-w-3xl mx-auto px-4 py-12 text-gray-900">
      <h1 className="text-3xl font-bold mb-4">Privacy Policy</h1>
      <p className="text-sm text-gray-500 mb-8">Last updated: August 23, 2025</p>
      <p className="mb-4">This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your information when you use the Codescholar Overseas website and tells you about your privacy rights and how the law protects you.</p>
      <p className="mb-4">We use your personal data to provide and improve the Service. By using the Service, you agree to the collection and use of information in accordance with this Privacy Policy.</p>
      <h2 className="text-xl font-semibold mt-8 mb-2">Interpretation and Definitions</h2>
      <h3 className="font-semibold mt-4 mb-1">Interpretation</h3>
      <p className="mb-4">Words with capitalized initial letters have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or plural.</p>
      <h3 className="font-semibold mt-4 mb-1">Definitions</h3>
      <p className="mb-4">For the purposes of this Privacy Policy:</p>
      <ul className="list-disc pl-6 mb-4 space-y-1">
        <li><b>Account</b> means a unique account created for you to access our Service or parts of our Service.</li>
        <li><b>Company</b> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Codescholar Overseas, West Nabanagar, Birati, Kolkata -700051, India.</li>
        <li><b>Cookies</b> are small files placed on your device by a website, containing details of your browsing history among its many uses.</li>
        <li><b>Country</b> refers to: West Bengal, India</li>
        <li><b>Device</b> means any device that can access the Service such as a computer, cellphone, or digital tablet.</li>
        <li><b>Personal Data</b> is any information that relates to an identified or identifiable individual.</li>
        <li><b>Service</b> refers to the Website (codescholaroverseas.com).</li>
        <li><b>Service Provider</b> means any natural or legal person who processes the data on behalf of the Company.</li>
        <li><b>Usage Data</b> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
        <li><b>You</b> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
      </ul>
      <h2 className="text-xl font-semibold mt-8 mb-2">Collecting and Using Your Personal Data</h2>
      <h3 className="font-semibold mt-4 mb-1">Types of Data Collected</h3>
      <p className="mb-2"><b>Personal Data</b></p>
      <p className="mb-4">While using our Service, we may ask you to provide us with certain personally identifiable information that can be used to contact or identify you. Personally identifiable information may include, but is not limited to: email address, phone number, and usage data.</p>
      <p className="mb-2"><b>Usage Data</b></p>
      <p className="mb-4">Usage Data is collected automatically when using the Service. This may include information such as your device’s IP address, browser type, browser version, the pages of our Service that you visit, the time and date of your visit, time spent on those pages, unique device identifiers, and other diagnostic data.</p>
      <h3 className="font-semibold mt-4 mb-1">Tracking Technologies and Cookies</h3>
      <p className="mb-4">We use cookies and similar tracking technologies to track the activity on our Service and store certain information. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent. However, if you do not accept cookies, you may not be able to use some parts of our Service.</p>
      <h2 className="text-xl font-semibold mt-8 mb-2">Use of Your Personal Data</h2>
      <ul className="list-disc pl-6 mb-4 space-y-1">
        <li>To provide and maintain our Service, including monitoring usage.</li>
        <li>To manage your Account and registration as a user.</li>
        <li>For the performance of a contract or to contact you.</li>
        <li>To provide you with news, special offers, and general information about our services.</li>
        <li>To manage your requests and for other business purposes such as data analysis and service improvement.</li>
      </ul>
      <h2 className="text-xl font-semibold mt-8 mb-2">Retention and Transfer of Your Personal Data</h2>
      <p className="mb-4">We will retain your Personal Data only as long as necessary for the purposes set out in this Privacy Policy. Your information may be transferred to — and maintained on — computers located outside of your state, province, country, or other governmental jurisdiction where the data protection laws may differ.</p>
      <h2 className="text-xl font-semibold mt-8 mb-2">Delete Your Personal Data</h2>
      <p className="mb-4">You have the right to delete or request that we assist in deleting the Personal Data that we have collected about you. Please contact us at <a href="mailto:info@codescholaroverseas.com" className="underline">info@codescholaroverseas.com</a> for such requests.</p>
      <h2 className="text-xl font-semibold mt-8 mb-2">Disclosure of Your Personal Data</h2>
      <ul className="list-disc pl-6 mb-4 space-y-1">
        <li>For business transactions (e.g., merger, acquisition, asset sale).</li>
        <li>To comply with legal obligations or law enforcement.</li>
        <li>To protect and defend the rights or property of the Company.</li>
        <li>To prevent or investigate possible wrongdoing in connection with the Service.</li>
        <li>To protect the personal safety of users or the public.</li>
        <li>With your consent.</li>
      </ul>
      <h2 className="text-xl font-semibold mt-8 mb-2">Security of Your Personal Data</h2>
      <p className="mb-4">The security of your Personal Data is important to us, but remember that no method of transmission over the Internet or electronic storage is 100% secure. While we strive to use commercially acceptable means to protect your Personal Data, we cannot guarantee its absolute security.</p>
      <h2 className="text-xl font-semibold mt-8 mb-2">Children’s Privacy</h2>
      <p className="mb-4">Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child has provided us with Personal Data, please contact us.</p>
      <h2 className="text-xl font-semibold mt-8 mb-2">Links to Other Websites</h2>
      <p className="mb-4">Our Service may contain links to other websites that are not operated by us. We strongly advise you to review the Privacy Policy of every site you visit. We have no control over and assume no responsibility for the content, privacy policies, or practices of any third party sites or services.</p>
      <h2 className="text-xl font-semibold mt-8 mb-2">Changes to this Privacy Policy</h2>
      <p className="mb-4">We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new Privacy Policy on this page. You are advised to review this Privacy Policy periodically for any changes. Changes are effective when they are posted on this page.</p>
      <h2 className="text-xl font-semibold mt-8 mb-2">Contact Us</h2>
      <p>If you have any questions about this Privacy Policy, you can contact us at <a href="mailto:info@codescholaroverseas.com" className="underline">info@codescholaroverseas.com</a>.</p>
    </div>
  );
}
